import 'package:flutter/material.dart';

enum AppLanguage { english, french, arabic }

class AppLanguageController extends ChangeNotifier {
  static final AppLanguageController instance = AppLanguageController._();

  AppLanguageController._();

  AppLanguage _current = AppLanguage.english;

  AppLanguage get current => _current;

  bool get isArabic => _current == AppLanguage.arabic;

  void changeLanguage(AppLanguage language) {
    if (_current == language) return;
    _current = language;
    notifyListeners();
  }

  String tr(String key) {
    return _translations[_current]?[key] ??
        _translations[AppLanguage.english]![key] ??
        _humanizeKey(key);
  }

  String _humanizeKey(String key) {
    final String normalized = key.replaceAll('_', ' ').trim();
    if (normalized.isEmpty) return key;
    return normalized
        .split(' ')
        .where((String word) => word.isNotEmpty)
        .map((String word) {
      final String lower = word.toLowerCase();
      return '${lower[0].toUpperCase()}${lower.substring(1)}';
    }).join(' ');
  }

  String trService(String serviceName) {
    final String key =
        'service_${serviceName.toLowerCase().replaceAll(' ', '_')}';
    return tr(key);
  }

  static const Map<AppLanguage, Map<String, String>> _translations = {
    AppLanguage.english: {
      'app_name': 'serviny',
      'open_chat': 'Open Chat',
      'get_started': 'Get Started',
      'home_hero': 'Easy, reliable way to take \ncare of your home',
      'home_desc': 'We provide you with the best people to help take care of your home.',
      'which_service': 'Which service \ndo you need?',
      'choose_offerer': 'Choose your offerer',
      'chat': 'Chat',
      'book': 'Book',
      'select_date': 'Select Date & Time',
      'provider': 'Provider',
      'base_price': 'Base Price',
      'total': 'Total',
      'additional_service': 'Additional Service',
      'repeat': 'Repeat',
      'language': 'Language',
      'french': 'French',
      'arabic': 'Arabic',
      'english': 'English',
      'service_cleaning': 'Cleaning',
      'service_plumber': 'Plumber',
      'service_electrician': 'Electrician',
      'service_painter': 'Painter',
      'service_carpenter': 'Carpenter',
      'service_gardener': 'Gardener',
      'service_tailor': 'Tailor',
      'service_maid': 'Maid',
      'service_driver': 'Driver',
      'service_cook': 'Cook',
      'service_ac_repair': 'AC Repair',
      'service_pest_control': 'Pest Control',
      'service_appliance_repair': 'Appliance Repair',
      'service_babysitting': 'Babysitting',
      'chat_welcome': 'Salem! I am {name}, your {service} in {city}.',
      'issue_noted': 'Issue noted',
      'first_quote': 'My first quote is',
      'negotiation_invite': 'We can discuss based on details and your budget.',
      'your_city': 'your city',
      'chat_urgent_reply': 'I understand it is urgent! I can prioritize your request in {city}. Let us agree on a price quickly.',
      'chat_deal_confirmed': 'I appreciate that! Deal confirmed at {price} TND. I will be there at the agreed time in {city}.',
      'chat_price_accepted': 'That works for me. I accept {price} TND for the work in {city}. Can you please confirm the booking?',
      'chat_min_price_reached': 'To be honest, {price} TND is the absolute minimum I can do for {city}. It takes a lot of time and travel.',
      'chat_counter_offer': 'I hear you, but my costs are high. How about we meet in the middle at {price} TND?',
      'chat_price_query': 'I usually charge around {price} TND for services in {city}. What kind of budget did you have in mind?',
      'chat_availability_reply': 'I am actually free this evening after 6 PM or tomorrow morning at 9 AM to visit you in {city}. Which one is better?',
      'chat_location_query': 'I work mostly in {provider_city} and I can definitely come to {city}. Where exactly are you located?',
      'chat_final_confirmation': 'Perfect! I have locked in the price at {price} TND. You can now confirm the booking using the icon above.',
      'chat_default_reply': 'Got it. I have handled many similar cases in {provider_city}. Should I proceed with the booking at {price} TND?',
      'typing': 'typing...',
      'online': 'Online',
      'client_chats': 'Client Chats',
      'no_messages_yet': 'No messages yet',
      'type_message': 'Type a message...',
      'confirm_booking': 'Confirm Booking',
      'mark_done': 'Mark as Done',
      'can_do_less': 'Can you do it for less?',
      'offer': 'Offer',
      'accept_current_quote': 'Accept current quote',
      'safety_center': 'Safety Center',
      'safety_confirm_label': 'I will verify identity, meet in a safe place, and keep emergency contact active.',
      'safety_tip_1': 'Meet in a public place when possible.',
      'safety_tip_2': 'Verify provider identity before allowing entry.',
      'safety_tip_3': 'Use in-app chat and report any abusive behavior immediately.',
      'report_abuse': 'Report Abuse',
      'report_submitted': 'Safety report submitted. Our team will follow up.',
      'emergency_call': 'Emergency Call',
      'emergency_help': 'Emergency support alerted. Call local authorities if needed.',
      'blocked_message_warning': 'Your message contains harmful language and was not sent.',
      'safety_ack_needed': 'Please enable the safety checklist before confirming.',
      'booking_confirmed_at': 'Booking confirmed at',
      'no_booking_found': 'No booking found for this provider yet.',
      'job_marked_done': 'Job marked as done. Please rate the provider.',
      'provider_dashboard': 'Provider Dashboard',
      'refresh_location': 'Refresh Location',
      'active_jobs_area': 'Active Jobs in your Area',
      'performance_insights': 'Performance Insights',
      'visibility_radius': 'Visibility Radius',
      'center_detecting': 'Center: Detecting GPS...',
      'no_active_requests_nearby': 'No active requests nearby.',
      'try_increase_radius': 'Try increasing your search radius.',
      'km_away': 'km away',
      'bid_accept': 'Bid / Accept',
      'weekly_revenue': 'Weekly Revenue',
      'active_receiving': 'Active & Receiving',
      'currently_inactive': 'Currently Inactive',
      'ready_new_requests': 'Ready for new requests',
      'switch_on_jobs': 'Switch on to see jobs',
      'jobs_done': 'Jobs Done',
      'pending': 'Pending',
      'reliability': 'Reliability',
      'earnings': 'Earnings',
      'history': 'History',
      'payouts': 'Payouts',
      'chats': 'Chats',
      'support': 'Support',
      'dashboard': 'Dashboard',
      'profile_cv': 'Profile & CV',
      'job_history': 'Job History',
      'technical_support': 'Technical Support',
      'account_settings': 'Account Settings',
      'logout': 'Logout',
      'offer_accepted': 'Offer accepted and booking added.',
      'accept_offer': 'Accept Offer',
      'chat_with_client': 'Chat with Client',
      'booking_confirmed_title': 'Booking Confirmed!',
      'booking_pending_with': 'Your booking is now pending with',
      'track_in_profile': 'You can track it in your profile.',
      'view_my_bookings': 'View My Bookings',
      'describe_more_here': 'Describe more here...',
      'urgent_request': 'Urgent Request',
      'standard_request': 'Standard Request',
      'urgent_response_hint': 'Provider will be notified to respond immediately.',
      'standard_response_hint': 'Normal response time applies.',
      'budget': 'Budget',
      'budget_example': 'e.g. 50',
      'id_verified': 'ID Verified',
      'emergency_contact': 'Emergency Contact',
      'auto_share_emergency_contact': 'Auto-share emergency contact for this booking',
      'safety_auto_shared_with': 'Safety contact auto-shared with',
      'emergency_contact_shared': 'Emergency contact shared in chat for safety.',
      'safety_check_in': 'Safety Check-In',
      'safety_check_in_prompt': 'Are you safe after this service?',
      'im_safe': 'I am safe',
      'need_help': 'Need help',
      'booking_step_1': 'Step 1: Details',
      'booking_step_2': 'Step 2: Schedule',
      'continue_to_schedule': 'Continue to Schedule',
      'back': 'Back',
      'live_booking_status': 'Live Booking Status',
      'status_pending': 'Pending',
      'no_active_booking': 'No active booking right now.',
      'quick_rebook': 'Quick Rebook',
      'arrival_code': 'Arrival code',
      'login': 'Login',
      'sign_up': 'Sign Up',
      'create_account': 'Create Account',
      'email': 'Email',
      'password': 'Password',
      'full_name': 'Full Name',
      'phone_number': 'Phone Number',
      'dont_have_account': 'Don\'t have an account?',
      'already_have_account': 'Already have an account?',
      'continue_as_guest': 'Continue as guest',
      'access_account_as': 'Access your account as a',
      'invalid_email': 'Please enter a valid email address.',
      'password_too_short': 'Password must contain at least 6 characters.',
      'invalid_name': 'Please enter a valid full name.',
      'i_need_service': 'I need a service',
      'i_am_provider': 'I am a service provider',
      'ask_for_address': 'Ask for address',
      'confirm_availability': 'Confirm availability',
      'client_thanks': 'Thanks, please proceed.',
      'client_accepts_small_over_budget': 'Okay, I can accept {price} TND if this includes all costs.',
      'client_counter_budget': 'My budget is around {price} TND. Can we do that?',
      'client_address_reply': 'Sure, I will share the exact address in the booking details.',
      'client_time_reply': 'I am available today after 6 PM.',
      'client_default_reply': 'Understood. I would like to stay near {price} TND.',
    },
    AppLanguage.french: {
      'app_name': 'serviny',
      'open_chat': 'Ouvrir le chat',
      'get_started': 'Commencer',
      'home_hero': 'Une facon simple et fiable de \nprendre soin de votre maison',
      'home_desc': 'Nous vous proposons les meilleurs prestataires pour votre maison.',
      'which_service': 'Quel service \naviez-vous besoin ?',
      'choose_offerer': 'Choisissez le prestataire',
      'chat': 'Discuter',
      'book': 'Reserver',
      'select_date': 'Choisir la date et l\'heure',
      'provider': 'Prestataire',
      'base_price': 'Prix de base',
      'total': 'Total',
      'additional_service': 'Service supplementaire',
      'repeat': 'Repetition',
      'language': 'Langue',
      'french': 'Francais',
      'arabic': 'Arabe',
      'english': 'Anglais',
      'service_cleaning': 'Nettoyage',
      'service_plumber': 'Plombier',
      'service_electrician': 'Electricien',
      'service_painter': 'Peintre',
      'service_carpenter': 'Menuisier',
      'service_gardener': 'Jardinier',
      'service_tailor': 'Couturier',
      'service_maid': 'Femme de menage',
      'service_driver': 'Chauffeur',
      'service_cook': 'Cuisinier',
      'service_ac_repair': 'Reparation climatiseur',
      'service_pest_control': 'Lutte antiparasitaire',
      'service_appliance_repair': 'Reparation electromenager',
      'service_babysitting': 'Garde d enfants',
      'chat_welcome': 'Salem ! Je suis {name}, votre {service} à {city}.',
      'issue_noted': 'Problème noté',
      'first_quote': 'Mon premier devis est de',
      'negotiation_invite': 'Nous pouvons en discuter selon les détails et votre budget.',
      'your_city': 'votre ville',
      'chat_urgent_reply': 'Je comprends que c\'est urgent ! Je peux donner la priorité à votre demande à {city}. Mettons-nous d\'accord sur un prix rapidement.',
      'chat_deal_confirmed': 'J\'apprécie cela ! Accord confirmé à {price} TND. Je serai là à l\'heure convenue à {city}.',
      'chat_price_accepted': 'Ça me va. J\'accepte {price} TND pour le travail à {city}. Pouvez-vous s\'il vous plaît confirmer la réservation ?',
      'chat_min_price_reached': 'Pour être honnête, {price} TND est le minimum absolu que je puisse faire pour {city}. Cela prend beaucoup de temps et de déplacement.',
      'chat_counter_offer': 'Je vous entends, mais mes coûts sont élevés. Que diriez-vous de nous retrouver au milieu à {price} TND ?',
      'chat_price_query': 'Je facture habituellement environ {price} TND pour des services à {city}. Quel genre de budget aviez-vous en tête ?',
      'chat_availability_reply': 'Je suis en fait libre ce soir après 18h ou demain matin à 9h pour vous rendre visite à {city}. Lequel est le mieux ?',
      'chat_location_query': 'Je travaille principalement à {provider_city} et je peux certainement venir à {city}. Où exactement êtes-vous situé ?',
      'chat_final_confirmation': 'Parfait ! J\'ai bloqué le prix à {price} TND. Vous pouvez maintenant confirmer la réservation en utilisant l\'icône ci-dessus.',
      'chat_default_reply': 'Compris. J\'ai traité de nombreux cas similaires à {provider_city}. Dois-je procéder à la réservation à {price} TND ?',
      'typing': 'écrit...',
      'online': 'En ligne',
      'client_chats': 'Chats clients',
      'no_messages_yet': 'Pas encore de messages',
      'type_message': 'Écrivez un message...',
      'confirm_booking': 'Confirmer réservation',
      'mark_done': 'Marquer terminé',
      'can_do_less': 'Pouvez-vous baisser le prix ?',
      'offer': 'Offre',
      'accept_current_quote': 'Accepter le prix actuel',
      'safety_center': 'Centre de sécurité',
      'safety_confirm_label': 'Je vérifie l\'identité, je choisis un lieu sûr et je garde un contact d\'urgence.',
      'safety_tip_1': 'Privilégiez un lieu public quand c\'est possible.',
      'safety_tip_2': 'Vérifiez l\'identité du prestataire avant l\'accès.',
      'safety_tip_3': 'Utilisez le chat de l\'app et signalez tout abus immédiatement.',
      'report_abuse': 'Signaler un abus',
      'report_submitted': 'Signalement envoyé. Notre équipe va suivre.',
      'emergency_call': 'Appel d\'urgence',
      'emergency_help': 'Alerte sécurité envoyée. Appelez les autorités si besoin.',
      'blocked_message_warning': 'Votre message contient un langage offensant et n\'a pas été envoyé.',
      'safety_ack_needed': 'Activez la checklist sécurité avant de confirmer.',
      'booking_confirmed_at': 'Réservation confirmée à',
      'no_booking_found': 'Aucune réservation trouvée pour ce prestataire.',
      'job_marked_done': 'Mission terminée. Merci de noter le prestataire.',
      'provider_dashboard': 'Tableau prestataire',
      'refresh_location': 'Actualiser localisation',
      'active_jobs_area': 'Demandes actives autour de vous',
      'performance_insights': 'Indicateurs de performance',
      'visibility_radius': 'Rayon de visibilité',
      'center_detecting': 'Centre : GPS en détection...',
      'no_active_requests_nearby': 'Aucune demande active proche.',
      'try_increase_radius': 'Essayez d\'augmenter le rayon.',
      'km_away': 'km de distance',
      'bid_accept': 'Proposer / Accepter',
      'weekly_revenue': 'Revenu hebdomadaire',
      'active_receiving': 'Actif et disponible',
      'currently_inactive': 'Actuellement inactif',
      'ready_new_requests': 'Prêt pour de nouvelles demandes',
      'switch_on_jobs': 'Activez pour voir les missions',
      'jobs_done': 'Missions réalisées',
      'pending': 'En attente',
      'reliability': 'Fiabilité',
      'earnings': 'Gains',
      'history': 'Historique',
      'payouts': 'Paiements',
      'chats': 'Chats',
      'support': 'Support',
      'dashboard': 'Tableau de bord',
      'profile_cv': 'Profil & CV',
      'job_history': 'Historique des missions',
      'technical_support': 'Support technique',
      'account_settings': 'Paramètres du compte',
      'logout': 'Déconnexion',
      'offer_accepted': 'Offre acceptée et réservation ajoutée.',
      'accept_offer': 'Accepter l\'offre',
      'chat_with_client': 'Discuter avec le client',
      'booking_confirmed_title': 'Réservation confirmée !',
      'booking_pending_with': 'Votre réservation est en attente avec',
      'track_in_profile': 'Vous pouvez la suivre dans votre profil.',
      'view_my_bookings': 'Voir mes réservations',
      'describe_more_here': 'Décrivez plus ici...',
      'urgent_request': 'Demande urgente',
      'standard_request': 'Demande standard',
      'urgent_response_hint': 'Le prestataire sera notifié immédiatement.',
      'standard_response_hint': 'Délai normal de réponse.',
      'budget': 'Budget',
      'budget_example': 'ex. 50',
      'id_verified': 'Identité vérifiée',
      'emergency_contact': 'Contact d\'urgence',
      'auto_share_emergency_contact': 'Partager automatiquement ce contact pour cette réservation',
      'safety_auto_shared_with': 'Contact sécurité partagé automatiquement avec',
      'emergency_contact_shared': 'Contact d\'urgence partagé dans le chat.',
      'safety_check_in': 'Vérification de sécurité',
      'safety_check_in_prompt': 'Êtes-vous en sécurité après cette prestation ?',
      'im_safe': 'Je suis en sécurité',
      'need_help': 'Besoin d\'aide',
      'booking_step_1': 'Étape 1 : Détails',
      'booking_step_2': 'Étape 2 : Horaire',
      'continue_to_schedule': 'Continuer vers l\'horaire',
      'back': 'Retour',
      'live_booking_status': 'Statut de réservation en direct',
      'status_pending': 'En attente',
      'no_active_booking': 'Aucune réservation active pour le moment.',
      'quick_rebook': 'Réserver à nouveau',
      'arrival_code': 'Code d\'arrivée',
      'login': 'Connexion',
      'sign_up': 'Inscription',
      'create_account': 'Créer un compte',
      'email': 'Email',
      'password': 'Mot de passe',
      'full_name': 'Nom complet',
      'phone_number': 'Numéro de téléphone',
      'dont_have_account': 'Vous n\'avez pas de compte ?',
      'already_have_account': 'Vous avez déjà un compte ?',
      'continue_as_guest': 'Continuer en invité',
      'access_account_as': 'Accédez à votre compte en tant que',
      'invalid_email': 'Veuillez entrer une adresse email valide.',
      'password_too_short': 'Le mot de passe doit contenir au moins 6 caractères.',
      'invalid_name': 'Veuillez entrer un nom complet valide.',
      'i_need_service': 'J\'ai besoin d\'un service',
      'i_am_provider': 'Je suis prestataire',
      'ask_for_address': 'Demander l\'adresse',
      'confirm_availability': 'Confirmer disponibilité',
      'client_thanks': 'Merci, vous pouvez continuer.',
      'client_accepts_small_over_budget': 'D\'accord, je peux accepter {price} TND si tout est inclus.',
      'client_counter_budget': 'Mon budget est autour de {price} TND. Possible ?',
      'client_address_reply': 'Bien sûr, je partagerai l\'adresse exacte dans la réservation.',
      'client_time_reply': 'Je suis disponible aujourd\'hui après 18h.',
      'client_default_reply': 'Compris. Je préfère rester proche de {price} TND.',
    },
    AppLanguage.arabic: {
      'app_name': 'سيرفيني',
      'open_chat': 'افتح الدردشة',
      'get_started': 'ابدأ',
      'home_hero': 'طريقة سهلة وموثوقة \nللعناية بمنزلك',
      'home_desc': 'نوفر لك افضل مقدمي الخدمات للعناية بالمنزل.',
      'which_service': 'ما هي الخدمة \nالتي تحتاجها؟',
      'choose_offerer': 'اختر مقدم الخدمة',
      'chat': 'دردشة',
      'book': 'احجز',
      'select_date': 'اختر التاريخ والوقت',
      'provider': 'مقدم الخدمة',
      'base_price': 'السعر الاساسي',
      'total': 'المجموع',
      'additional_service': 'خدمات اضافية',
      'repeat': 'التكرار',
      'language': 'اللغة',
      'french': 'الفرنسية',
      'arabic': 'العربية',
      'english': 'الانجليزية',
      'service_cleaning': 'تنظيف',
      'service_plumber': 'سباك',
      'service_electrician': 'كهربائي',
      'service_painter': 'دهان',
      'service_carpenter': 'نجار',
      'service_gardener': 'بستاني',
      'service_tailor': 'خياط',
      'service_maid': 'عاملة منزل',
      'service_driver': 'سائق',
      'service_cook': 'طباخ',
      'service_ac_repair': 'اصلاح المكيف',
      'service_pest_control': 'مكافحة الحشرات',
      'service_appliance_repair': 'اصلاح الاجهزة',
      'service_babysitting': 'مجالسة اطفال',
      'chat_welcome': 'سالم! أنا {name}، مقدم خدمة {service} الخاص بك في {city}.',
      'issue_noted': 'تم ملاحظة المشكلة',
      'first_quote': 'سعري الأولي هو',
      'negotiation_invite': 'يمكننا المناقشة بناءً على التفاصيل وميزانيتك.',
      'your_city': 'مدينتك',
      'chat_urgent_reply': 'أفهم أن الأمر مستعجل! يمكنني إعطاء الأولوية لطلبك في {city}. دعنا نتفق على السعر بسرعة.',
      'chat_deal_confirmed': 'أقدر ذلك! تم تأكيد الاتفاق بسعر {price} دينار. سأكون هناك في الوقت المتفق عليه في {city}.',
      'chat_price_accepted': 'هذا يناسبني. أقبل {price} دينار مقابل العمل في {city}. هل يمكنك من فضلك تأكيد الحجز؟',
      'chat_min_price_reached': 'بصراحة، {price} دينار هو الحد الأدنى المطلق الذي يمكنني القيام به لـ {city}. الأمر يتطلب الكثير من الوقت والسفر.',
      'chat_counter_offer': 'أسمعك، لكن تكاليفي مرتفعة. ما رأيك أن نلتقي في المنتصف عند {price} دينار؟',
      'chat_price_query': 'عادةً ما أتقاضى حوالي {price} دينار مقابل الخدمات في {city}. ما نوع الميزانية التي كانت في ذهنك؟',
      'chat_availability_reply': 'أنا في الواقع متفرغ هذا المساء بعد الساعة 6 مساءً أو صباح الغد في الساعة 9 صباحاً لزيارتك في {city}. أيهما أفضل؟',
      'chat_location_query': 'أعمل غالباً في {provider_city} ويمكنني بالتأكيد القدوم إلى {city}. أين تقع بالضبط؟',
      'chat_final_confirmation': 'ممتاز! لقد قمت بتثبيت السعر عند {price} دينار. يمكنك الآن تأكيد الحجز باستخدام الأيقونة أعلاه.',
      'chat_default_reply': 'فهمت. لقد تعاملت مع العديد من الحالات المماثلة في {provider_city}. هل يجب أن أستمر في الحجز بسعر {price} دينار؟',
      'typing': 'يكتب...',
      'online': 'متصل',
      'client_chats': 'دردشات العملاء',
      'no_messages_yet': 'لا توجد رسائل بعد',
      'type_message': 'اكتب رسالة...',
      'confirm_booking': 'تأكيد الحجز',
      'mark_done': 'تحديد كمكتمل',
      'can_do_less': 'هل يمكن تخفيض السعر؟',
      'offer': 'عرض',
      'accept_current_quote': 'قبول السعر الحالي',
      'safety_center': 'مركز الأمان',
      'safety_confirm_label': 'سأتحقق من الهوية وأختار مكاناً آمناً وأبقي جهة اتصال طوارئ.',
      'safety_tip_1': 'يفضل اللقاء في مكان عام عند الإمكان.',
      'safety_tip_2': 'تحقق من هوية مقدم الخدمة قبل الدخول.',
      'safety_tip_3': 'استخدم دردشة التطبيق وأبلغ فوراً عن أي إساءة.',
      'report_abuse': 'الإبلاغ عن إساءة',
      'report_submitted': 'تم إرسال البلاغ وسيتم المتابعة.',
      'emergency_call': 'اتصال طوارئ',
      'emergency_help': 'تم تنبيه فريق الأمان. اتصل بالسلطات عند الحاجة.',
      'blocked_message_warning': 'رسالتك تحتوي لغة مسيئة ولم يتم إرسالها.',
      'safety_ack_needed': 'يرجى تفعيل قائمة الأمان قبل التأكيد.',
      'booking_confirmed_at': 'تم تأكيد الحجز عند',
      'no_booking_found': 'لا يوجد حجز لهذا المزود بعد.',
      'job_marked_done': 'تم إنهاء المهمة. يرجى تقييم مقدم الخدمة.',
      'provider_dashboard': 'لوحة مقدم الخدمة',
      'refresh_location': 'تحديث الموقع',
      'active_jobs_area': 'الطلبات النشطة في منطقتك',
      'performance_insights': 'مؤشرات الأداء',
      'visibility_radius': 'نطاق الظهور',
      'center_detecting': 'المركز: جاري تحديد GPS...',
      'no_active_requests_nearby': 'لا توجد طلبات قريبة حالياً.',
      'try_increase_radius': 'حاول زيادة نطاق البحث.',
      'km_away': 'كم بعيد',
      'bid_accept': 'تقديم / قبول',
      'weekly_revenue': 'الإيراد الأسبوعي',
      'active_receiving': 'نشط ويستقبل',
      'currently_inactive': 'غير نشط حالياً',
      'ready_new_requests': 'جاهز لطلبات جديدة',
      'switch_on_jobs': 'فعّل لرؤية الطلبات',
      'jobs_done': 'المهام المنجزة',
      'pending': 'قيد الانتظار',
      'reliability': 'الاعتمادية',
      'earnings': 'الأرباح',
      'history': 'السجل',
      'payouts': 'المدفوعات',
      'chats': 'الدردشات',
      'support': 'الدعم',
      'dashboard': 'لوحة التحكم',
      'profile_cv': 'الملف الشخصي والسيرة',
      'job_history': 'سجل المهام',
      'technical_support': 'الدعم الفني',
      'account_settings': 'إعدادات الحساب',
      'logout': 'تسجيل الخروج',
      'offer_accepted': 'تم قبول العرض وإضافة الحجز.',
      'accept_offer': 'قبول العرض',
      'chat_with_client': 'الدردشة مع العميل',
      'booking_confirmed_title': 'تم تأكيد الحجز!',
      'booking_pending_with': 'حجزك الآن قيد الانتظار مع',
      'track_in_profile': 'يمكنك متابعته من ملفك الشخصي.',
      'view_my_bookings': 'عرض حجوزاتي',
      'describe_more_here': 'اكتب تفاصيل أكثر هنا...',
      'urgent_request': 'طلب مستعجل',
      'standard_request': 'طلب عادي',
      'urgent_response_hint': 'سيتم إشعار مقدم الخدمة فوراً.',
      'standard_response_hint': 'يطبق وقت الاستجابة العادي.',
      'budget': 'الميزانية',
      'budget_example': 'مثال: 50',
      'id_verified': 'هوية موثقة',
      'emergency_contact': 'جهة اتصال للطوارئ',
      'auto_share_emergency_contact': 'مشاركة جهة الطوارئ تلقائياً لهذا الحجز',
      'safety_auto_shared_with': 'تمت مشاركة جهة الأمان تلقائياً مع',
      'emergency_contact_shared': 'تمت مشاركة جهة الطوارئ في الدردشة لأسباب أمان.',
      'safety_check_in': 'تحقق الأمان',
      'safety_check_in_prompt': 'هل أنت بخير بعد هذه الخدمة؟',
      'im_safe': 'أنا بخير',
      'need_help': 'أحتاج مساعدة',
      'booking_step_1': 'الخطوة 1: التفاصيل',
      'booking_step_2': 'الخطوة 2: الموعد',
      'continue_to_schedule': 'المتابعة إلى الموعد',
      'back': 'رجوع',
      'live_booking_status': 'حالة الحجز المباشرة',
      'status_pending': 'قيد الانتظار',
      'no_active_booking': 'لا يوجد حجز نشط حالياً.',
      'quick_rebook': 'إعادة الحجز بسرعة',
      'arrival_code': 'رمز الوصول',
      'login': 'تسجيل الدخول',
      'sign_up': 'إنشاء حساب',
      'create_account': 'إنشاء حساب',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'full_name': 'الاسم الكامل',
      'phone_number': 'رقم الهاتف',
      'dont_have_account': 'ليس لديك حساب؟',
      'already_have_account': 'لديك حساب بالفعل؟',
      'continue_as_guest': 'المتابعة كضيف',
      'access_account_as': 'ادخل إلى حسابك كـ',
      'invalid_email': 'يرجى إدخال بريد إلكتروني صحيح.',
      'password_too_short': 'يجب أن تكون كلمة المرور 6 أحرف على الأقل.',
      'invalid_name': 'يرجى إدخال اسم كامل صحيح.',
      'i_need_service': 'أحتاج خدمة',
      'i_am_provider': 'أنا مقدم خدمة',
      'ask_for_address': 'طلب العنوان',
      'confirm_availability': 'تأكيد التوفر',
      'client_thanks': 'شكراً، يمكنك المتابعة.',
      'client_accepts_small_over_budget': 'حسناً، يمكنني قبول {price} دينار إذا كان كل شيء مشمولاً.',
      'client_counter_budget': 'ميزانيتي حوالي {price} دينار. هل يمكن؟',
      'client_address_reply': 'أكيد، سأشارك العنوان الدقيق في تفاصيل الحجز.',
      'client_time_reply': 'أنا متاح اليوم بعد السادسة مساءً.',
      'client_default_reply': 'مفهوم. أفضّل البقاء قريباً من {price} دينار.',
    },
  };
}
